repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^locale/
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args: [--check, --diff]
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
