name: Deploy Latest

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Install doctl 🌊
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Authenticate to DigitalOcean 🔐
        run: doctl registry login --expiry-seconds 600

      - name: Deploy 🚀
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
