name: Update Translations

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update-translations:
    name: Update Translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Download translations 🌐
        uses: crowdin/github-action@v1.6.0
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          commit_message: "feat: new translations"
          create_pull_request: true
          pull_request_title: "feat: new translations"
          pull_request_labels: l10n
          config: ./crowdin.yml
          source: locale/en_GB/LC_MESSAGES/pdf_bot.po
          translation: /locale/%locale_with_underscore%/LC_MESSAGES/pdf_bot.po
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
